---
title: "hw1_key"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
needs(tidyverse, rio, here, misty, psych, rstatix)
hw <- read.sav(here("data/HW1_ereader.sav"), use.value.labels = T)
```

# Descriptives
```{r}
describe(hw)

describeBy(hw, group = hw$Condition, mat = T)
```


```{r}
ggplot(hw, aes(x = ReadingTime)) +
  geom_histogram()

ggplot(hw, aes(x = Condition, y = ReadingTime)) +
  geom_boxplot()
```


```{r}
levene_test(hw, ReadingTime ~ Condition, center = "mean")
```

# ANOVA
```{r, eval = F}
needs(powerAnalysis)
anova <- anova_test(data = hw, formula =  ReadingTime ~ Condition,
           effect.size = "pes", detailed = TRUE, type = 3)
anova
m1 <- hw %>%  
  group_by(Condition) %>%  
  summarise_at(vars(ReadingTime),
               list(name = mean)) %>% 
  select(name)
m1
power.anova.test(groups = 4, n = 20, between.var = bg, within.var = wg, sig.level = .05)

needs(pingouin)


effectsize::cohens_f(anova)

cohens_f(car::Anova(ReadingTime ~ Condition, hw))
cohens_f(car::Anova(fit, type = 3))



etasq <- 462967.7/(21308716.2+1332877+462967.7) 
f = EtaSQ / (1-EtaSQ)

pwr.f2.test(u = 4, v = 16, f = f, sig.level = .05)

pwr.anova.test(k = 4, n = 5, f = f, sig.level = .05)



fit <- lm(ReadingTime ~ Condition, hw)

anova(fit)
wg<- anova(fit)["Residuals", "Mean Sq"]
bg <-  anova(fit)["Condition", "Mean Sq"]
bg
```

```{r, eval = F}
m1 <- lm(ReadingTime ~ Condition, hw)

means <- emmeans(m1, ~ Condition)
means

contrasts <- list(
  hyp1 = c(1, -.33, -.33, -.34),
  hyp2 = c(1, -1, 0, 0),
  hyp3 = c(0, 1, -1, 0),
  hyp4 = c(0, 0, 1, -1)
)

contrast(means, contrasts, adjust = "bonferroni")

effectsize::t_to_eta2(
  t = c(0.0681),
  df_error = 16
)
```
