---
title: "EDUC 640"
subtitle: "Two-Way Factorial ANOVA"
author: Chris Ives
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
needs(tidyverse, xaringan, rio, here, misty, emmeans, rstatix)
hw2 <- read.sav(here("data/HW2_ereader.sav"), use.value.labels = T)
```


# Calculate Marginal Means

```{r}
means <- hw2 %>% 
  group_by(Device, Condition) %>% 
  summarise(ReadingTime = mean(ReadingTime))
```

# Boxplots
```{r}
ggplot(means, aes(x = Device, y = ReadingTime, group = Condition)) +
  geom_point() +
  geom_line(aes(color = Condition))
```

# Specify Model
```{r}
model <- lm(ReadingTime ~ Device + Condition + Device:Condition, hw2)
means_1 <- emmeans(model, ~Device*Condition)
```

```{r}
pairs(means_1)
```

## Specifying contrasts
```{r}
means_1
```
 
```{r}
contrasts <- list(
  hyp1 = c(1, -.5, -.5, rep(0, 6), -1, .5, .5))
```
`rep(0, 6)` means repeat "0" six times.

```{r}
contrast(means_1, contrasts, adjust = "holm")
```

## Effect Size
```{r}
effectsize::t_to_eta2(
  t = 0.084,
  df_error = 48
)
```
